メンタリング質問対応
================
まずは出力されたエラーに注目してみましょう．
~~~
----> 5 np.dot(a,b)

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)
~~~
と出ていますが，これはまず，
~~~
5行目「np.dot(a,b)」でエラーが発生しました．
~~~
ということと，具体的なエラー内容
~~~
1行3列の行列と1行3列の行列では，1つめの行列の列数と2つ目の行列の行数が一致していません．
~~~
ということを教えてくれています．